const data = [
  {
    id: 1,
    short_name: "Kung Pao Chicken",
    long_name: "Long Name",
    image_path: "/images/img24.png",
    rating: 4.5,
    price: "553.00",
    short_description: "dfgf",
    long_description: "fgf",
    category_data: "Chinese",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "gf",
    allergen: "gff",
    calorie: "3",
    protein: "3",
    carbs: "3",
    fat: "3",
    sugar: "3",
    salt: "3",
    additional_information: "dfdf",
    start_date_of_expiry: "2020-11-09",
    end_date_of_expiry: "2020-11-05",
  },
  {
    id: 2,
    short_name: "Ma Po Tofu",
    long_name: "special Ma Po Tofu",
    image_path: "/images/img25.png",
    rating: 4,
    price: "553.00",
    short_description: "dfgf",
    long_description: "fgf",
    category_data: "Chinese",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "gf",
    allergen: "gff",
    calorie: "3",
    protein: "3",
    carbs: "3",
    fat: "3",
    sugar: "3",
    salt: "3",
    additional_information: "dfdf",
    start_date_of_expiry: "2020-11-09",
    end_date_of_expiry: "2020-11-05",
  },
  {
    id: 3,
    short_name: "Short Name",
    long_name: "Long Name",
    image_path: "/images/img26.png",
    rating: 3,
    price: "553.00",
    short_description: "dfgf",
    long_description: "fgf",
    category_data: "Pakistani",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "gf",
    allergen: "gff",
    calorie: "3",
    protein: "3",
    carbs: "3",
    fat: "3",
    sugar: "3",
    salt: "3",
    additional_information: "dfdf",
    start_date_of_expiry: "2020-11-09",
    end_date_of_expiry: "2020-11-05",
  },
  {
    id: 4,
    short_name: "Lasagne",
    long_name: "Lasagne",
    image_path: "/images/img27.jpg",
    rating: 5,
    price: "557.00",
    short_description: "dfgf",
    long_description: "fgf",
    category_data: "Italian",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "gf",
    allergen: "gff",
    calorie: "3",
    protein: "3",
    carbs: "3",
    fat: "3",
    sugar: "3",
    salt: "3",
    additional_information: "dfdf",
    start_date_of_expiry: "2020-11-09",
    end_date_of_expiry: "2020-11-05",
  },
  {
    id: 5,
    short_name: "biryani",
    long_name: "special biryani",
    image_path: "/images/img28.jpg",
    rating: 2,
    price: "123.00",
    short_description: "testt",
    long_description: "testtt",
    category_data: "Pakistani",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "testtt",
    allergen: "testt",
    calorie: "12",
    protein: "555",
    carbs: "555",
    fat: "55",
    sugar: "5",
    salt: "5",
    additional_information: "66",
    start_date_of_expiry: "2020-12-31",
    end_date_of_expiry: "2020-12-31",
  },
  {
    id: 6,
    short_name: "Pasta",
    long_name: "special pasta",
    image_path: "/images/img29.jpg",
    rating: 3.5,
    price: "123.00",
    short_description: "testt",
    long_description: "testtt",
    category_data: "Italian",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "testtt",
    allergen: "testt",
    calorie: "12",
    protein: "555",
    carbs: "555",
    fat: "55",
    sugar: "5",
    salt: "5",
    additional_information: "66",
    start_date_of_expiry: "2020-12-31",
    end_date_of_expiry: "2020-12-31",
  },
  {
    id: 7,
    short_name: "Carpaccio",
    long_name: "special Carpaccio",
    image_path: "/images/img30.jpg",
    rating: 4.2,
    price: "123.00",
    short_description: "testt",
    long_description: "testtt",
    category_data: "Italian",
    attribute_data: ["lactose", "abc", "vegan"],
    ingredient: "testtt",
    allergen: "testt",
    calorie: "12",
    protein: "555",
    carbs: "555",
    fat: "55",
    sugar: "5",
    salt: "5",
    additional_information: "66",
    start_date_of_expiry: "2020-12-31",
    end_date_of_expiry: "2020-12-31",
  },
];

export default data;
